// Comprehensive Transpiler - All target languages
// JavaScript, Python, CSS, HTML, C++, C#, Rust, WASM, JSON

import { Parser } from '../parser/parser-core.js'

export type TargetLanguage = 'javascript' | 'python' | 'css' | 'html' | 'cpp' | 'csharp' | 'rust' | 'wasm' | 'json' | 'asm'

export interface TranspilerOptions {
  target: TargetLanguage
  framework?: 'react' | 'vue' | 'angular' | 'unity' | 'node' | 'django' | 'flask'
  indent?: string
}

export class NebularaTranspiler {
  private parser: Parser
  private indent: string

  constructor(options?: TranspilerOptions) {
    this.parser = new Parser()
    this.indent = options?.indent || '  '
  }

  transpile(code: string, options: TranspilerOptions): string {
    const ast = this.parser.parse(code)
    return this.generate(ast, options)
  }

  private generate(ast: any, options: TranspilerOptions): string {
    switch (options.target) {
      case 'javascript': return this.toJavaScript(ast, options)
      case 'python': return this.toPython(ast, options)
      case 'css': return this.toCSS(ast)
      case 'html': return this.toHTML(ast)
      case 'cpp': return this.toCPP(ast)
      case 'csharp': return this.toCSharp(ast, options)
      case 'rust': return this.toRust(ast)
      case 'wasm': return this.toWASM(ast)
      case 'json': return this.toJSON(ast)
      case 'asm': return this.toAssembly(ast)
      default: return this.toJavaScript(ast, options)
    }
  }

  private toJavaScript(ast: any, options: TranspilerOptions): string {
    const lines: string[] = ['// Generated by Nebulara', '']

    const walk = (node: any, level = 0) => {
      const pad = this.indent.repeat(level)
      
      switch (node.type) {
        case 'Program':
          node.body?.forEach((n: any) => walk(n, level))
          break

        case 'App':
          lines.push(`${pad}// Nebulara App: ${node.name}`)
          if (options.framework === 'react') {
            lines.push(`${pad}function App() {`)
          }
          node.body?.forEach((n: any) => walk(n, options.framework === 'react' ? level + 1 : level))
          if (options.framework === 'react') {
            lines.push(`${pad}}`)
          }
          break

        case 'Run':
          node.body?.forEach((n: any) => walk(n, level))
          break

        case 'Print':
          const msg = node.expression?.value || ''
          lines.push(`${pad}console.log("${msg}")`)
          break

        case 'If':
          lines.push(`${pad}if (${this.expr(node.condition)}) {`)
          node.consequent?.forEach((n: any) => walk(n, level + 1))
          lines.push(`${pad}}`)
          if (node.alternate) {
            lines.push(`${pad}else {`)
            node.alternate.forEach((n: any) => walk(n, level + 1))
            lines.push(`${pad}}`)
          }
          break

        case 'While':
          lines.push(`${pad}while (${this.expr(node.condition)}) {`)
          node.body?.forEach((n: any) => walk(n, level + 1))
          lines.push(`${pad}}`)
          break

        case 'Loop':
          lines.push(`${pad}while (true) {`)
          node.body?.forEach((n: any) => walk(n, level + 1))
          lines.push(`${pad}}`)
          break

        case 'Assign':
          const val = node.value?.value ?? node.value?.name ?? node.value
          lines.push(`${pad}const ${node.name} = ${val}`)
          break

        case 'Func':
          lines.push(`${pad}function ${node.name}(${node.params?.join(', ') || ''}) {`)
          node.body?.forEach((n: any) => walk(n, level + 1))
          lines.push(`${pad}}`)
          break
      }
    }

    walk(ast)
    return lines.join('\n') + '\n'
  }

  private expr(node: any): string {
    if (!node) return 'true'
    if (node.type === 'Number') return node.value
    if (node.type === 'Binary') return `(${this.expr(node.left)} ${node.operator} ${this.expr(node.right)})`
    return 'true'
  }

  private toPython(ast: any, options: TranspilerOptions): string {
    const lines: string[] = ['# Generated by Nebulara']

    const walk = (node: any) => {
      switch (node.type) {
        case 'Program':
          node.body?.forEach(walk)
          break
        case 'App':
          lines.push(`# App: ${node.name}`)
          node.body?.forEach(walk)
          break
        case 'Run':
          node.body?.forEach(walk)
          break
        case 'Print':
          const msg = node.expression?.value || ''
          lines.push(`print("${msg}")`)
          break
        case 'If':
          lines.push(`if ${this.expr(node.condition)}:`)
          node.consequent?.forEach(walk)
          if (node.alternate) {
            lines.push('else:')
            node.alternate.forEach(walk)
          }
          break
        case 'Assign':
          lines.push(`${node.name} = ${node.value?.value ?? 'null'}`)
          break
      }
    }

    walk(ast)
    return lines.join('\n') + '\n'
  }

  private toCSS(ast: any): string {
    const lines: string[] = ['.nebulara {', '  /* Generated by Nebulara */', '}']

    const walk = (node: any) => {
      if (node.type === 'Identifier') {
        lines.push(`\n.${node.value} {`)
        lines.push('  /* TODO */')
        lines.push('}')
      }
    }

    ast.body?.forEach(walk)
    return lines.join('\n') + '\n'
  }

  private toHTML(ast: any): string {
    const lines: string[] = ['<!DOCTYPE html>', '<html>', '<body>', '  <!-- Generated by Nebulara -->', '</body>', '</html>']

    const walk = (node: any) => {
      if (node.type === 'App') {
        lines.splice(3, 0, `  <h1>${node.name}</h1>`)
      }
    }

    ast.body?.forEach(walk)
    return lines.join('\n') + '\n'
  }

  private toCPP(ast: any): string {
    const lines: string[] = ['#include <iostream>', 'using namespace std;', '', 'int main() {']

    const walk = (node: any) => {
      switch (node.type) {
        case 'Print':
          const msg = node.expression?.value || ''
          lines.push(`  cout << "${msg}" << endl;`)
          break
      }
    }

    ast.body?.forEach(walk)
    lines.push('  return 0;', '}')
    return lines.join('\n') + '\n'
  }

  private toCSharp(ast: any, options: TranspilerOptions): string {
    const using = options.framework === 'unity' ? 'using UnityEngine;' : ''
    const lines: string[] = ['using System;', using, '', 'public class Program {', '  static void Main() {']

    const walk = (node: any) => {
      if (node.type === 'Print') {
        const msg = node.expression?.value || ''
        lines.push(`    Console.WriteLine("${msg}");`)
      }
    }

    ast.body?.forEach(walk)
    lines.push('  }', '}')
    return lines.join('\n') + '\n'
  }

  private toRust(ast: any): string {
    const lines: string[] = ['fn main() {']

    const walk = (node: any) => {
      if (node.type === 'Print') {
        const msg = node.expression?.value || ''
        lines.push(`  println!("${msg}");`)
      }
    }

    ast.body?.forEach(walk)
    lines.push('}')
    return lines.join('\n') + '\n'
  }

  private toWASM(ast: any): string {
    const lines: string[] = ['(module', '  (func $main (export "_start")', '    ;; Generated by Nebulara', '  )', ')']
    return lines.join('\n') + '\n'
  }

  private toJSON(ast: any): string {
    const json: any = { type: 'Program', body: [] }
    
    const walk = (node: any) => {
      json.body.push({ type: node.type, ...node })
    }

    ast.body?.forEach(walk)
    return JSON.stringify(json, null, 2) + '\n'
  }

  private toAssembly(ast: any): string {
    const { SSAEmitter } = require('../ir/ir-ssa.js')
    const emitter = new SSAEmitter('prog')
    const ssa = emitter.generate(ast)
    return `; Generated Nebulara Assembly\n${ssa.blocks.map((b: any) =>
      b.instructions.map((i: any) => `  ; ${i.op} ${i.args?.join(' ') || ''}`).join('\n')
    ).join('\n')}\n`
  }
}