[package]
name = "nebulara"
version = "1.2.0"
edition = "2021"
description = "Nebulara - AI-native universal programming language"
license = "UNLICENSED"
repository = "https://github.com/CODURRALABS/NEBULARA"
readme = "README.md"
keywords = ["compiler", "programming-language", "ai-native"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "nebulara"
path = "src/main.rs"
