// Void Conversational AI — Unified Frontier Engine
// No training required — Pure symbolic reasoning + NLP + Knowledge Graph

import { NLPCore } from './nlp/core.mjs';
import { KnowledgeBase } from './nlp/knowledge.mjs';
import { ReasoningEngine } from './nlp/reasoning.mjs';
import { ResponseGenerator } from './nlp/generator.mjs';
import { ConversationManager } from './nlp/conversation.mjs';

class VoidAI {
  constructor(options = {}) {
    // Core components
    this.nlp = new NLPCore();
    this.kb = new KnowledgeBase();
    this.reasoning = new ReasoningEngine(this.kb);
    this.generator = new ResponseGenerator(this.nlp, this.kb, this.reasoning);
    this.conversations = new ConversationManager(
      options.maxHistory || 50,
      options.maxContextTokens || 4000
    );

    // State
    this.activeSession = null;
    this.stats = {
      totalMessages: 0,
      totalSessions: 0,
      averageResponseTime: 0,
      topicsDiscussed: new Set()
    };

    // Initialize
    this._init();
  }

  _init() {
    console.log('[Void AI] Initializing frontier conversational engine...');
    console.log('[Void AI] NLP Core: Ready (rule-based, zero training)');
    console.log(`[Void AI] Knowledge Base: ${this.kb.stats().facts} facts, ${this.kb.stats().concepts} concepts`);
    console.log(`[Void AI] Reasoning: Deduction, Induction, Abduction, Analogy`);
    console.log('[Void AI] Status: Ready for conversation');
  }

  // ============================================
  // MAIN API
  // ============================================

  /**
   * Start a new conversation session
   */
  startSession(userId = 'default') {
    const sessionId = this.conversations.createSession(userId);
    this.activeSession = sessionId;
    this.stats.totalSessions++;

    // Add greeting
    this.conversations.addMessage(sessionId, 'assistant', this.generator.personality.greeting, {
      type: 'greeting',
      autoGenerated: true
    });

    return {
      sessionId,
      greeting: this.generator.personality.greeting
    };
  }

  /**
   * Send a message and get a response
   */
  chat(message, sessionId = null) {
    const start = performance.now();
    const sid = sessionId || this.activeSession;

    if (!sid) {
      // Auto-create session
      const session = this.startSession();
      return this.chat(message, session.sessionId);
    }

    // Analyze input
    const analysis = {
      intent: this.nlp.recognizeIntent(message),
      entities: this.nlp.extractEntities(message),
      sentiment: this.nlp.analyzeSentiment(message),
      keywords: this.nlp.extractKeywords(message)
    };

    // Add user message
    this.conversations.addMessage(sid, 'user', message, analysis);

    // Build context
    const contextWindow = this.conversations.buildContextWindow(sid);
    const session = this.conversations.getSession(sid);

    // Generate response
    const response = this.generator.generate(message, {
      conversation: session.context,
      contextWindow,
      user: session.memory.facts.get('userName') ? { name: session.memory.facts.get('userName') } : null
    });

    // Add assistant response
    this.conversations.addMessage(sid, 'assistant', response.text, {
      type: response.type,
      confidence: response.confidence,
      suggestions: response.suggestions
    });

    // Update stats
    const responseTime = performance.now() - start;
    this.stats.totalMessages++;
    this.stats.averageResponseTime = (this.stats.averageResponseTime * (this.stats.totalMessages - 1) + responseTime) / this.stats.totalMessages;

    // Track topics
    for (const keyword of analysis.keywords) {
      this.stats.topicsDiscussed.add(keyword.word);
    }

    return {
      response: response.text,
      type: response.type,
      confidence: response.confidence,
      suggestions: response.suggestions || [],
      sessionId: sid,
      metadata: {
        responseTime: responseTime.toFixed(2) + 'ms',
        analysis: {
          intent: analysis.intent.primary.intent,
          sentiment: analysis.sentiment.label,
          entities: analysis.entities.map(e => `${e.type}: ${e.value}`)
        }
      }
    };
  }

  /**
   * Get conversation history
   */
  getHistory(sessionId = null, lastN = null) {
    const sid = sessionId || this.activeSession;
    return this.conversations.getHistory(sid, lastN);
  }

  /**
   * Get session statistics
   */
  getSessionStats(sessionId = null) {
    const sid = sessionId || this.activeSession;
    return this.conversations.getSessionStats(sid);
  }

  /**
   * Get global stats
   */
  getStats() {
    let sessionStats = null;
    if (this.activeSession) {
      try {
        sessionStats = this.conversations.getSessionStats(this.activeSession.id);
      } catch (e) {
        sessionStats = { messageCount: this.stats.totalMessages, topicsDiscussed: [...this.stats.topicsDiscussed] };
      }
    }
    return {
      ...this.stats,
      topicsDiscussed: [...this.stats.topicsDiscussed],
      knowledgeBase: this.kb.stats(),
      activeSession: this.activeSession,
      conversation: sessionStats
    };
  }

  /**
   * Add knowledge to the system
   */
  addKnowledge(entity, attributes) {
    return this.kb.addFact(entity, attributes);
  }

  /**
   * Add a concept definition
   */
  addConcept(name, definition, related = [], examples = []) {
    return this.kb.addConcept(name, definition, related, examples);
  }

  /**
   * Add a relation
   */
  addRelation(subject, predicate, object) {
    return this.kb.addRelation(subject, predicate, object);
  }

  /**
   * Ask a direct question (without conversation context)
   */
  ask(question) {
    return this.chat(question);
  }

  /**
   * Get available topics
   */
  getTopics() {
    return [...this.stats.topicsDiscussed];
  }

  /**
   * End session
   */
  endSession(sessionId = null) {
    const sid = sessionId || this.activeSession;
    const stats = this.conversations.endSession(sid);
    if (sid === this.activeSession) {
      this.activeSession = null;
    }
    return stats;
  }

  // ============================================
  // ADVANCED API
  // ============================================

  /**
   * Reason about a topic
   */
  reason(topic) {
    const inferred = this.reasoning.infer(topic);
    const explanation = this.reasoning.explain(topic);
    const related = this.kb.getRelatedEntities(topic);

    return {
      topic,
      facts: this.kb.getFact(topic),
      inferred,
      explanation,
      related
    };
  }

  /**
   * Compare two topics
   */
  compare(topic1, topic2) {
    const facts1 = this.kb.getFact(topic1) || {};
    const facts2 = this.kb.getFact(topic2) || {};

    const analogies = this.reasoning.analogize(topic1, topic2);

    return {
      topic1,
      topic2,
      facts1,
      facts2,
      analogies
    };
  }

  /**
   * Search knowledge base
   */
  search(query) {
    const concepts = this.kb.searchConcepts(query);
    const facts = this.kb.queryFacts({ entity: query });

    return {
      query,
      concepts,
      facts
    };
  }
}

export { VoidAI };
