// Nebulara Native Compiler - Complete Implementation
// Generates NASM x86-64 assembly for Linux/Windows

import { Parser } from '../parser/parser-core.js'
import { SSAEmitter, SSAProgram } from '../ir/ir-ssa.js'

export class NativeCompiler {
  private target: 'linux' | 'windows'
  private output: string[]

  constructor(target: 'linux' | 'windows' = 'linux') {
    this.target = target
    this.output = []
  }

  compile(source: string): string {
    // 1. Parse to AST
    const parser = new Parser()
    const ast = parser.parse(source)
    
    // 2. Generate SSA IR
    const emitter = new SSAEmitter('program')
    const ssa = emitter.generate(ast)
    
    // 3. Generate assembly
    return this.generateAssembly(ssa)
  }

  private generateAssembly(ssa: SSAProgram): string {
    const lines: string[] = []
    const strings: string[] = []
    const printIndices: number[] = []
    
    // First pass: extract strings and map PRINT indices
    for (const block of ssa.blocks) {
      for (const instr of block.instructions) {
        if (instr.op === 'PRINT' && instr.args[0] && instr.args[0].startsWith('"')) {
          const msg = instr.args[0].slice(1, -1)
          strings.push(msg)
          printIndices.push(strings.length - 1)
        } else {
          printIndices.push(-1) // non-print instruction
        }
      }
    }
    
    // Header
    lines.push('; Generated by Nebulara Native Compiler')
    lines.push('BITS 64')
    lines.push('DEFAULT REL')
    lines.push('')
    
    // Data section
    lines.push('SECTION .data')
    strings.forEach((s, i) => {
      lines.push(`msg${i} db "${this.escapeString(s)}", 10, 0`)
    })
    lines.push('')
    
    // Text section
    lines.push('SECTION .text')
    lines.push('GLOBAL _start')
    lines.push('')
    lines.push('_start:')
    
    // Second pass: emit instructions with correct indices
    let pi = 0
    for (const block of ssa.blocks) {
      lines.push(`  ; Block: ${block.label}`)
      for (const instr of block.instructions) {
        const isPrint = instr.op === 'PRINT' && printIndices[pi] >= 0
        this.emitAssemblyInstruction(instr, lines, isPrint ? printIndices[pi] : -1)
        pi++
      }
    }
    
    // Exit
    lines.push('')
    lines.push('  ; Exit syscall')
    if (this.target === 'linux') {
      lines.push('  mov rax, 60')
      lines.push('  xor rdi, rdi')
      lines.push('  syscall')
    } else {
      lines.push('  xor eax, eax')
      lines.push('  ret')
    }
    
    return lines.join('\n')
  }

  private escapeString(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
  }

  private emitAssemblyInstruction(instr: any, lines: string[], msgIndex: number): void {
    if (instr.op === 'COMMENT') {
      lines.push(`  ; ${instr.args[0]}`)
      return
    }
    if (instr.op === 'PRINT' && instr.args[0]) {
      const msg = instr.args[0].replace(/"/g, '') || ''
      lines.push('  mov rax, 1')
      lines.push('  mov rdi, 1')
      lines.push(`  lea rsi, [rel msg${msgIndex}]`)
      lines.push(`  mov rdx, ${msg.length || 0}`)
      lines.push('  syscall')
      return
    }
    lines.push(`  ; ${instr.op} ${instr.args?.join(' ') || ''}`)
  }

  compileToFile(source: string, outputPath: string): void {
    const asm = this.compile(source)
    require('fs').writeFileSync(outputPath, asm)
    console.log(`Generated: ${outputPath}`)
  }
}